### ISSUE TITLE
Doesn't Work In Production

### ISSUE THREAD

**Issue by Oliver-Turp** [devpanther/better-react-carousel#3]
Worked fine in development but the second I ran a production build, I get `Cannot read properties of undefined (reading 'withConfig')` error and the site breaks. Remove your carousel and the site works again, yours is the only sttyle component I have. 

Any advice would be great because this is the best carousel I found during development tests.

**Comment by xermate** [comment]
+1 to this. same issue in production

**Comment by steve958** [comment]
Has anyone made any progress with this issue?

**Comment by devpanther** [comment]
> Worked fine in development but the second I ran a production build, I get `Cannot read properties of undefined (reading 'withConfig')` error and the site breaks. Remove your carousel and the site works again, yours is the only sttyle component I have.
> 
> Any advice would be great because this is the best carousel I found during development tests.

Is this a NextJS environment?

**Comment by Oliver-Turp** [comment]
Iirc, I was using Vite at that stage. I migrated to Nextjs since but I don't think I was using as far back as Sept 2022

**Comment by itsabishiek** [comment]
I found that, this problem is coming from styled-compenents and you can fix it. Since you're using rollup, change the following code.

// rollup.config.js
export default {
  // ...
  output: {
    interop: 'auto',
  },
};

So kindly update these @devpanther . Thanks in advance

**Comment by amantpcg01** [comment]
> I found that, this problem is coming from styled-compenents and you can fix it. Since you're using rollup, change the following code.
> 
> // rollup.config.js export default { // ... output: { interop: 'auto', }, };
> 
> So kindly update these @devpanther . Thanks in advance

Brother, can you explain in brief please?

**Comment by devpanther** [comment]
> I found that, this problem is coming from styled-compenents and you can fix it. Since you're using rollup, change the following code.
> 
> // rollup.config.js
> export default {
>   // ...
>   output: {
>     interop: 'auto',
>   },
> };
> 
> So kindly update these @devpanther . Thanks in advance
> 

Thank you @itsabishiek for this finding.. I'd check it out and update the library asap
