### ISSUE TITLE
Carousel.Item Using in map()

### ISSUE THREAD

**Issue by kimberlyydanij** [devpanther/better-react-carousel#5]
Hello. Thank you for sharing your perfect library.
It really helps to me as a beginner developer.

I would like to use this library with map() function but I have a problem with "key"
How can I use this with map()?

 <Carousel.Item key={id}>

because of key error, I could get data from backend but it doesn't showing on the browser.

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

import '../css/bootstrap.min.css';
import '../css/style.css';
import '../css/carousel.css';
import { useEffect, useState } from 'react';

import axios from 'axios';
import Carousel from 'better-react-carousel';
import { baseUrl } from '../components/commonApi/mainApi';

const NewestSmall = () => {
  const [book, setbook] = useState([]);
  const addr = baseUrl + '/newest';
  console.log(addr);

  useEffect(() => {
    getbook();
  }, []);

  async function getbook() {
    await axios
      .get(addr)
      .then((response) => {
        setbook(response.data);
      })
      .catch((error) => {
        console.log(error);
      });
  }

  return (
    <div className='neweast container col-xl-6 col-lg-6'
      <div className='carousel container-fluid mt-4'
        <Carousel cols={2} rows={1} gap={15} loop
          <div
            {book.map((book) => {
              return (
                <Carousel.Item key={book.book_num}
                  <div id='book-image'
                    <a href={'/book/' + book.book_num}
                      <img src={book.book_image} alt={book.book_title} /
                    </a
                  </div
                  <div
                    <p id='book-ranking'>#1</p
                    <p id='book-title'>{book.book_title}</p
                    <p id='book-category'>{book.category_code}</p
                  </div
                </Carousel.Item
              );
            })}
            ;
          </div
        </Carousel
      </div
    </div
  );
};

export default NewestSmall;

**Comment by devpanther** [comment]
Hey @kimberlyydanij, Thanks for the issue

Can you properly format the codes please?

**Comment by ilamin** [comment]
@kimberlyydanij change book.map((book) to book.map((bookmap) then <Carousel.Item key={bookmap.book_num}
@devpanther nice library 👏👏👏

**Comment by ilamin** [comment]
@kimberlyydanij change book.map((book) to book.map((bookmap) then <Carousel.Item key={bookmap.book_num}
@devpanther nice library 👏👏👏
